core/urls.py
from django.urls import path
from . import views

app_name = 'category'
urlpatterns = [
    # path('', views.index)
    path('', views.IndexHome.as_view(), name='index'),
    path('cart', views.DetailCard.as_view(), name='index'),
    path('category/create', views.CreateCategory.as_view(), name='create'),
    path('category/detail/<int:pk>', views.DetailCategory.as_view(), name='detail'),
    path('category/update/<int:pk>', views.UpdateCategory.as_view(), name='update'),
    path('account/register/',views.Register, name='register'),
    path('account/login/',views.Login, name='login'),
    path('account/logout',views.Logout, name='logout'),
    path('api/product/<int:id>',views.DetailProductApi),
    path('api/checkout',views.Checkout),
]

linhkiendientu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

core/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
# Create your models here.

IS_DELETED_CHOICES = (
    (0, "Chưa xóa"),
    (1, "Đã xóa")
)

ROLE_CHOICES = (
    (1, 'Admin'),
    (2, 'Nhân viên'),
    (3, 'Khách hàng')
)

ORDER_STATUS_CHOICES = (
    (1, 'Chờ xác nhận'),
    (2, 'Đã xác nhận'),
    (3, 'Đã giao'),
    (4, 'Đã hủy đơn')
)

class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Tên danh mục')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_deleted = models.IntegerField(choices=IS_DELETED_CHOICES, default=0, max_length=1)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=254)
    price = models.BigIntegerField(default=0)
    quantity = models.IntegerField(default=0, blank=True, null=True)
    descr = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_deleted = models.IntegerField(choices=IS_DELETED_CHOICES, default=0)

    def __str__(self):
        return self.name
    class Meta:
        ordering = ['name']

class Image(models.Model):    
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    url = models.ImageField(null=False, blank=True, upload_to='photos')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_deleted = models.IntegerField(choices=IS_DELETED_CHOICES, default=0)
    def admin_photo(self):
        return mark_safe('<img src="{}" width=100px;height=150px />'.format(self.image.url))
    admin_photo.short_description = 'image'
    admin_photo.allow_tags = True

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    phone = models.CharField(max_length=12)
    address = models.CharField(max_length=254)
    total_price = models.BigIntegerField(default=0)
    note = models.TextField(blank=True, null=True)
    order_status = models.IntegerField(choices= ORDER_STATUS_CHOICES, default=1)
    product = models.ManyToManyField(Product, through='OrderDetail')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_deleted = models.IntegerField(choices=IS_DELETED_CHOICES, default=0)

class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.BigIntegerField(default=0)
    note = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_deleted = models.IntegerField(choices=IS_DELETED_CHOICES, default=0)

core/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.http import HttpResponse, HttpRequest,HttpResponseRedirect, JsonResponse
from django.views.generic import ListView, CreateView, FormView, View, DetailView, UpdateView
from django.urls import reverse_lazy
from .models import Category, Product, Order, OrderDetail, User, Image
from core.form import RegisterForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
import json
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
# def index(request):
#     return render(request, 'pages/main.html')

class IndexHome(ListView):
    template_name = 'pages/main.html'
    context_object_name = 'listView'

    def get_queryset(self):
        listObject = {
            'categoryList' : Category.objects.all(),
            'productList' : Product.objects.all(),
            'imageList': Image.objects.all()
        }
        return listObject

class CreateCategory(CreateView):
    model = Category
    fields = ['name']
    template_name = 'pages/formCreate.html'
    success_url = reverse_lazy('category:index')

class DetailCategory(DetailView):
    model = Product
    template_name = 'pages/product__detail.html'

class UpdateCategory(UpdateView):
    model = Category
    fields = ['name']
    template_name = 'pages/formCreate.html'
    success_url = reverse_lazy('category:index')

class DetailCard(ListView):
    model = Product
    template_name = 'pages/cart.html'
    context_object_name = 'listView'


def DetailProductApi(request, id):
    product = Product.objects.get(id = id)
    if not product:
        return JsonResponse(
            {
                "err_code": 232,
                "err_msg": "Khong tim thay san pham",
            }
        )
    return JsonResponse(
            {
                "err_code": 0,
                "err_msg": "Thành công",
                "data": {
                    "id": id,
                    "name": product.name,
                    "quantity": product.quantity,
                    "price": product.price,
                    "descr": product.descr,
                }
            }
        )
@csrf_exempt
def Checkout(request):
    if not request.user.is_authenticated:
        return JsonResponse(
            {
                "err_code": 403,
                "err_msg": "Chua dang nhap",
                "data": {
                    
                    
                }
            }
        )

    data = json.loads(request.body)
    name = data['name']
    phone = data['phone']
    address = data['address']
    total_price = data['total_price']
    note = data['note']
    items = data['items']
    # user = User.objects.get(id=1)
    order = Order.objects.create(user=request.user, name=name, phone=phone, address=address, total_price=total_price, note=note)
    order.save()
    for item in items:
        product = Product.objects.get(id=item['product_id'])
        orderDetail = OrderDetail.objects.create(order=order, product=product, quantity=item['quantity'], price=item['price'])
        orderDetail.save()
    return JsonResponse(
            {
                "err_code": 0,
                "err_msg": "Thành công",
                "data": {
                    "id": order.id,
                },
                "user": request.user.id
            }
        )

def Register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('../accounts/login')
    return render (request, 'registration/register.html',{'form': form})
def Login(request):
    if request.method == 'POST':
        if  request.user.is_authenticated:
            messages.warning(request, "Bạn đã đăng nhập")
            return redirect('')
        else:
            if request.method == 'POST':
                name = request.POST.get('username') 
                password = request.POST.get('password') 
                user = authenticate(request, username=name, password=password)
                if user is not None:
                    login(request, user)
                    messages.success(request, "Đăng nhập thành công")
                    return redirect('category:index')
                else:
                    messages.error(request, "Tài khoản hoặc mật khẩu không chính xác!!!")
                    return redirect('category:login')     
    return render(request, "registration/login.html") 

def Logout(request):
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, "Đăng xuất thành công")
    return redirect("category:index")

core/templates/adminn/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}
    {% endblock %}</title>
    {% include "adminn/styles.html" %}
</head>
<body class="hold-transition sidebar-mini text-sm sidebar-collapse">
    <div class="wrapper">
        {% include "adminn/header.html" %}
        {% include "adminn/sidebar.html" %}
        <div class="content-wrapper">
            {% block main %}
            {% endblock %}
        </div>
        {% include "adminn/footer.html" %}
    </div>
    {% include "adminn/script.html" %}
</body>
</html>

core/templates/adminn/categories.html
{% extends "adminn/base.html" %}
{% load static %}      
    {% block title %}
    LKDT. - Danh Mục
    {% endblock %}
    {% block categories %}
    <section class="content-header">
        <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>DataTables</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">DataTables</li>
                        </ol>
                    </div>
                </div>
        </div>
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">DataTable with minimal features & hover style</h3>
                        </div>
                        <div class="card-body">
                            <table id="CategoryTable" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Tên danh mục</th>
                                        <th>Hành động</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th>Tên danh mục</th>
                                        <th>Hành động</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
    const loadDataApi = async () => {
        let dataCategories = await getDataAPI('https://localhost:7299/api/categories');
        if (dataCategories == null) {
            alert('Sự cố kết nối đến api');
            return;
        }
        if (dataCategories.success) {
            loadDataToTable(dataCategories.data);
        } else {
            alert(`Lỗi: ${dataCategories.message}`);
        }
    }
    const loadDataToTable = (listCategories) => {
        let elementTable = document.querySelector('#CategoryTable .tbody');

    }
    </script>
    <script src="{% static 'js/Category/Index.js'%}" asp-append-version="true"></script>
    {% endblock  %}

core/templates/adminn/footer.html
{% load static %}    
    <footer class="main-footer">
        <strong>Copyright &copy; @DateTime.Now.Year <a href="javascript:void(0);">Linh Kiện Điện Tử Management</a>.</strong> All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            <b>Version 1.0.0</b> 
        </div>
    </footer>

core/templates/adminn/header.html
{% load static %}  
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        {% include "adminn/header__left-navbar.html" %}
        {% include "adminn/header__right-navbar.html" %}
    </nav>

core/templates/adminn/header__left-navbar.html
{% load static %}
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
        </li>
    </ul>

core/templates/adminn/header__right-navbar.html
{% load static %}
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown nav-user-menu">
            <a href="javascript:void(0);" class="nav-link" data-toggle="dropdown" role="button">
                <img class="user-image img-circle elevation-2" style="width: 60px;" src="{% static 'lib/dist/img/avatar5.png'%}" alt="User Image">
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" >
                    <i class="fas fa-user-edit"></i> Cập nhật mật khẩu
                </a>
                <a class="dropdown-item">
                    <i class="fas fa-sign-out-alt"></i> Đăng Xuất
                </a>
            </div>
        </li>
    </ul>

core/templates/adminn/main.html
{% extends "adminn/base.html" %}
{% load static %}
    {% block title %}
    LKDT. - Admin
    {% endblock %}
    {% block main %}

    {% endblock %}

core/templates/adminn/script.html
{% load static %}
    <script src="{% static 'assets/js/lib_dtp000.js'%}"></script>
    <script src="{% static 'plugins/jquery/jquery.min.js'%}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.js'%}"></script>
    <!-- DataTables  & Plugins -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.js'%}"></script>
    <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.js'%}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.js'%}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.js'%}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.js'%}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.js'%}"></script>
    <script src="{% static 'plugins/jszip/jszip.js'%}"></script>
    <script src="{% static 'plugins/pdfmake/pdfmake.js'%}"></script>
    <script src="{% static 'plugins/pdfmake/vfs_fonts.js'%}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.html5.js'%}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.print.js'%}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.js'%}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/dist/js/adminlte.js'%}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'lib/dist/js/demo.js'%}"></script>

    <script src="~/js/Category/Index.js" asp-append-version="true"></script>
    <script>
        const loadDataApi = async () => {
            let dataCategories = await getDataAPI('https://localhost:7299/api/categories');
            if (dataCategories == null) {
                alert('Sự cố kết nối đến api');
                return;
            }
            if (dataCategories.success) {
                loadDataToTable(dataCategories.data);
            } else {
                alert(`Lỗi: ${dataCategories.message}`);
            }
        }
        const loadDataToTable = (listCategories) => {
            let elementTable = document.querySelector('#CategoryTable tbody');
            listCategories.forEach(category => {
                const wrapper = document.createElement('tr')
                wrapper.innerHTML = [
                    `<td>${category.name}</td>`,
                    `<td><button type="button" class="btn btn-sm bg-warning" data-toggle="modal" data-target="#ChucVuViewModal" >
                            <i class="fas fa-eye" ></i>
                        </button>
                        <button type="button" class="btn btn-sm bg-warning view-chucvu" data-toggle="modal" data-target="#ChucVuViewModal" >
                                    <i class="fas fa-pencil-alt" ></i>
                        </button>
                    </td>`,
                    ``
                ].join('');
                elementTable.appendChild(wrapper);
            })
        }
        const showModalData = (nodeCurrent) => {
            let modalData = document.getElementById('modal-category-info');

        }
        $(document).ready(function () {
            loadDataApi();
            //$('#CategoryTable').DataTable({

            //});
        });
        </script>

core/templates/adminn/sidebar.html
{% load static %}
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        {% include "adminn/sidebar__logo.html" %}
        <div class="sidebar">
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img src="{% static 'lib/dist/img/avatar5.png'%}" class="img-circle elevation-2" alt="User Image">
                </div>
                <div class="info">
                    <a class="d-block" href="javascript:void(0);">Admin</a>
                </div>
            </div>
        <nav class="mt-2">
        
        </nav>
        </div>
    </aside>

core/templates/adminn/sidebar__logo.html
{% load static %}
    <a class="brand-link" asp-controller="Home" asp-action="Index">
        <img src="{% static 'lib/dist/img/AdminLTELogo.png'%}" alt="Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Linh Kiện Điện Tử</span>
    </a>

core/templates/adminn/styles.html
{% load static %}
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback" asp-append-version="true">
    <!-- Font Awesome -->
    <link href="{% static 'plugins/fontawesome-free/css/all.min.css'%}" rel="stylesheet" asp-append-version="true">
    <!-- DataTables -->
    <!-- Theme style -->
    <link href="{% static 'lib/dist/css/adminlte.min.css'%}" rel="stylesheet" asp-append-version="true">
    <link href="{% static 'css/site.css'}" rel="stylesheet" asp-append-version="true"/>
    <link rel="icon" href="{% static 'assets/img/favicon.png'%}" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jqc-1.12.4/dt-1.13.2/b-2.3.4/sl-1.6.0/datatables.min.css"/>
    

core/templates/pages/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock  %}</title>
    {% include "pages/styles.html" %}
</head>
<body>
    <header>
        <div class="top-header border-bottom">
            <div class="container">
                <div class="row py-2">
                    <div class="col ">
                        Hotline: <a class="text-decoration-none text-primary fw-bold url" href="tel:+84901174550">090 117 4550</a>
                    </div>
                    <div class="col">
                        <div class="text-end">
                            <ul class="list-inline mb-0">
                                <li class="list-inline-item"><a class="text-decoration-none url" href="/admin">Đăng nhập Admin</a></li>
                                {% if user.is_authenticated %}
                                    <li class="list-inline-item"><a class="text-decoration-none url">Chào, {{ user.username }}.</a></li>
                                    <li class="list-inline-item"><a class="text-decoration-none url" href="{% url 'category:logout'%}">Đăng xuất</a></li>
                                {% else %}
                                    <li class="list-inline-item"><a class="text-decoration-none url" href="/account/register">Đăng ký</a></li>
                                    <li class="list-inline-item"><a class="text-decoration-none url" href="/account/login">Đăng nhập</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% include "pages/header.html" %}
    </header>
    <div class="container">
        {% block main %}
        {% endblock %}
    </div>
    {% include "pages/footer.html" %}
    {% include "pages/script.html" %}
    {% block add_script %}
    {% endblock %}
</body>
</html>

core/templates/pages/cart.html
{% load static %}
{% block cart %}
    <div class="bread-crumb">
        <div class="container">
            <div class="row">
                <div class="mt-2" style="-bs-breadcrumb-divider: '&gt;&gt;';"
                    aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">Trang chủ</li>
                        <li class="breadcrumb-item active text-primary" aria-current="page">Giỏ hàng</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
{% endblock  %}

core/templates/pages/categories__detail.html
{% load static %}  
{% block categories__detail %}
    <div class="bread-crumb">
	<div class="container">
		<div class="row">
			<div class="mt-2" style="-bs-breadcrumb-divider: '&gt;&gt;';"
				aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item">Trang chủ</li>
					<li class="breadcrumb-item active text-primary" aria-current="page">@Model.Category</li>
				</ol>
			</div>
		</div>
	</div>
</div>
<!-- end breadcrumb -->

<!-- Chuyên mục sản phẩm -->
    <div class="search">
        <div class="container">

            <div class="row">
                <div class="my-3">
                <h1 class="fs-4 text-uppercase page-title">@Model.Category</h1>
                </div>
            </div>
            
            <div class="row mt-4">
                <div class="col-md-3 col-sm-6 col-6">
                    <div class="row">
                        <div class="card h-100 product">
                            <a href="Products/Details/@item.Id" class="product-url" title="@Html.DisplayFor(modelItem => item.NameP)">
                                <img src="@Html.DisplayFor(modelItem => item.Image)" alt="@Html.DisplayFor(modelItem => item.NameP)">
                            </a>
                            <div class="card-body product-info">
                                <h3 class="product-name text-truncate ">
                                    <a class="text-decoration-none text-primary" href="Products/Details/@item.Id">@Html.DisplayFor(modelItem => item.NameP)</a>
                                </h3>
                                <div class="product-price">
                                    <span class="text-primary fw-bold">@Html.DisplayFor(modelItem => item.Price)₫</span>
                                </div>
                                <div class="review">
                                    <span class="active"><i class="fa fa-star" aria-hidden="true"></i></span>
                                    <span class="active"><i class="fa fa-star" aria-hidden="true"></i></span>
                                    <span class="active"><i class="fa fa-star" aria-hidden="true"></i></span>
                                    <span class="active"><i class="fa fa-star" aria-hidden="true"></i></span>
                                    <span class="active"><i class="fa fa-star" aria-hidden="true"></i>
                                    <small class="text-secondary">(9 đánh giá)</small></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock  %}

core/templates/pages/detailCategory.html
{% extends "pages/base.html" %}
{% block main %}
    <ul>
        <li>Tên sản phẩm: {{ product.name }}</li>
        <li>Giá sản phẩm: {{ product.price }}</li>
        <li>{{ product.quantity }}</li>
        <li>{{ product.created }}</li>
        <li>{{ product.updated }}</li>
        <li>{{ product.is_deleted }}</li>
        <li>Của danh mục: {{ product.category.name }}</li>
    </ul>
{% endblock %}

core/templates/pages/footer.html
{% load static %}
    <footer class="bg-primary mt-5">
        <div class="container-md">
            <div class="row py-3 justify-content-around">
                <div class="col-md-5 col-lg-4 col-sm-6 col-12">
                    <div class="logo text-center">
                        <a asp-area="" asp-controller="Home" asp-action="Index">
                            <img src="{% static 'assets/img/logoft.png'%}" alt="logo footer Linh Kiện Điện Tử">
                        </a>
                    </div>
                    <div class="content mt-2 text-center">
                        <p class="text-white">
                            Điện tử tuyên quang là web site bán hàng online chuyên cung cấp mạch điện tử, linh kiện điện tử chất lượng cao
                        </p>
                    </div>
                </div>
                <div class="col-md-5 col-lg-4 col-sm-6 col-12">
                    <ul class="ms-3 list-group bg-primary list-group-flush">
                        <li class="list-group-item bg-primary border-0 text-white pb-3 fs-6 fw-bold text-uppercase">Giới thiệu</li>
                        <li class="list-group-item bg-primary border-white text-white">Trang chủ</li>
                        <li class="list-group-item bg-primary border-white text-white">Tất cả sản phẩm</li>
                        <li class="list-group-item bg-primary border-white text-white">Linh kiện</li>
                        <li class="list-group-item bg-primary border-white text-white">Mạch điện tử</li>
                        <li class="list-group-item bg-primary border-white text-white">Thanh toán và vận chuyển</li>
                        <li class="list-group-item bg-primary border-white text-white">Blog</li>
                    </ul>
                </div>

                <div class="col-md-5 col-lg-4 col-sm-6 col-12">
                    <div class="ms-4 fb-title">
                        <p class="text-white text-uppercase fw-bold fs-6 mt-2">Kết nối trên Facebook</p>
                    </div>
                    <div class="ms-4 page-fb">
                        <span style="vertical-align: bottom; width: 263px; height: 150px;">

                        </span>
                    </div>
                </div>
                <div class="border-bottom my-4"></div>
                <div class="col-md-5 col-lg-4 col-sm-6 col-12">
                    <ul class="ms-3 list-group bg-primary list-group-flush mt-3">
                        <li class="list-group-item bg-primary p-0 ps-3 border-0 text-white pb-1 fs-6 fw-bold text-uppercase">Điện tử</li>
                        <li class="list-group-item bg-primary p-0 ps-3 border-0 text-white">Địa chỉ: Phú Thuận, Phú Vang, Thừa Thiên Huế</li>
                        <li class="list-group-item bg-primary p-0 ps-3 border-0 text-white">Hotline: <a class="text-white fw-bold" href="tel:0901174550">0901174550</a></li>
                        <li class="list-group-item bg-primary p-0 ps-3 border-0 text-white">Kỹ thuật: <a class="text-white fw-bold" href="tel:086591412">0865914142</a></li>
                        <li class="list-group-item bg-primary p-0 ps-3 border-0 text-white">Email: <a class="text-white fw-bold" href="mailto:khoicantk@gmail.com">khoicantk@gmail.com</a></li>
                    </ul>
                </div>
                <div class="d-block d-sm-none">
                    <div class="border-bottom my-4">
                    </div>
                </div>
                <div class="d-none d-sm-block d-md-none">
                    <div class="border-bottom my-4">
                    </div>
                </div>
                <div class="col-md-5 col-lg-4 col-sm-6 col-12">
                    <ul class="ms-3 list-inline bg-primary mt-3">
                        <li class="list-group-item bg-primary border-0 text-white pb-1 fs-6 fw-bold text-uppercase">Chấp nhận thanh toán</li>
                        <li class="list-inline-item ps-3 border-0">
                            <a href="#">
                                <img class="img-fluid" src="https://bizweb.dktcdn.net/100/184/656/themes/821115/assets/pay_1.png?1623059007493" alt="">
                            </a>
                        </li>
                        <li class="list-inline-item border-0">
                            <a href="#">
                                <img class="img-fluid" src="https://bizweb.dktcdn.net/100/184/656/themes/821115/assets/pay_2.png?1623059007493" alt="">
                            </a>
                        </li>
                        <li class="list-inline-item border-0">
                            <a href="#">
                                <img class="img-fluid" src="https://bizweb.dktcdn.net/100/184/656/themes/821115/assets/pay_3.png?1623059007493" alt="">
                            </a>
                        </li>
                        <li class="list-inline-item border-0">
                            <a href="#">
                                <img class="img-fluid" src="https://bizweb.dktcdn.net/100/184/656/themes/821115/assets/pay_4.png?1623059007493" alt="">
                            </a>
                        </li>
                        <li class="list-inline-item border-0">
                            <!-- <a href="#">
                                <img class="img-fluid" src="https://bizweb.dktcdn.net/100/184/656/themes/821115/assets/pay_5.png?1623059007493" alt="">
                            </a> -->
                        </li>
                    </ul>

                </div>
                <div class="col-md-5 col-lg-4 col-sm-6 col-12">
                    <ul class="ms-3 list-group bg-primary mt-3">
                        <li class="list-group-item bg-primary border-0 text-white pb-1 fs-6 fw-bold text-uppercase">Khiếu nại & Chăm sóc khách hàng</li>
                        <li class="list-group-item border-0 cskh bg-primary">
                            <a class="sdt-cskh text-white" href="tel:+84865914142">08 659 14142</a>
                            <span></span>
                        </li>

                    </ul>

                </div>
            </div>
            <div class="border-bottom my-2"></div>
            <div class="row">
                <div class="text-center text-white mt-2">
                    <p>&copy; Bản quyền thuộc về DTP000 - 2021</p>
                </div>
            </div>
        </div>
    </footer>